// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRns35Xtjm3TD5jA5pA1Jrg792pt6DXXk',
    appId: '1:596896838723:web:6b2ba40ac29e480dced0f6',
    messagingSenderId: '596896838723',
    projectId: 'mechanicspartner',
    authDomain: 'mechanicspartner.firebaseapp.com',
    storageBucket: 'mechanicspartner.appspot.com',
    measurementId: 'G-FSLX6GRNVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR4sGawMrO6PMThK2CWZCrQABx74QW-ig',
    appId: '1:596896838723:android:0bc4328500a718dbced0f6',
    messagingSenderId: '596896838723',
    projectId: 'mechanicspartner',
    storageBucket: 'mechanicspartner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyZTyWzbWRGyH_lSlyqemBycRZZRf6ves',
    appId: '1:596896838723:ios:96d78269b6e667f9ced0f6',
    messagingSenderId: '596896838723',
    projectId: 'mechanicspartner',
    storageBucket: 'mechanicspartner.appspot.com',
    iosClientId: '596896838723-j3jrqkm7tqsom9jkqni9uuvgjl0mpmj1.apps.googleusercontent.com',
    iosBundleId: 'cpm.namma.mechanics.partner',
  );
}
